apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
  - name: api
    image: ankur512512/eqworks-api
    ports:
    - containerPort: 5000
    env:
    - name: SQL_URI
      value: "postgresql://postgres:postgres@eqworks-postgres:5432/work_samples"
